# Generated by Django 2.2.6 on 2020-02-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='category',
            field=models.CharField(max_length=30),
        ),
    ]
