# Generated by Django 2.2.6 on 2020-02-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200222_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='category',
            field=models.CharField(choices=[('M', 'mobile'), ('T', 'tv'), ('G', 'grocery')], max_length=30),
        ),
    ]
