# Generated by Django 2.2.6 on 2020-02-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200222_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='image',
            field=models.ImageField(upload_to='media/products_images/'),
        ),
    ]
