# Generated by Django 2.2.6 on 2020-02-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200222_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='category',
            field=models.CharField(choices=[('Mobile', 'mobile'), ('Tv', 'tv'), ('Grocery', 'grocery')], max_length=30),
        ),
    ]
