# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-12-12 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'PYTHON'), ('Django', 'DJANGO'), ('Ui', 'UI'), ('RestAPI', 'REST API')], max_length=300)),
                ('trainers', multiselectfield.db.fields.MultiSelectField(choices=[('Sai', 'SAI'), ('Nani', 'NANI'), ('Satya', 'SATYA')], max_length=300)),
                ('branches', multiselectfield.db.fields.MultiSelectField(choices=[('Hyd', 'HYDERABAD'), ('Bang', 'BANGALORE'), ('Pune', 'PUNE')], max_length=300)),
                ('date', models.DateField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
