# Generated by Django 2.2.6 on 2019-10-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppartmentDetails',
            fields=[
                ('app_type', models.CharField(max_length=100)),
                ('app_no', models.IntegerField(primary_key=True, serialize=False)),
                ('app_area', models.DecimalField(decimal_places=2, max_digits=20)),
                ('app_floor_type', models.CharField(max_length=100)),
                ('app_age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlotDetails',
            fields=[
                ('plot_no', models.IntegerField(primary_key=True, serialize=False)),
                ('plot_image', models.ImageField(upload_to='plot/images/')),
                ('road_no', models.IntegerField()),
                ('survey_no', models.IntegerField()),
                ('cost_per_sqd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('other_exp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boundaries', models.IntegerField()),
                ('facing', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('Total_cost', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
