# Generated by Django 2.2.6 on 2019-10-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectdetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotdetails',
            name='plot_image',
            field=models.ImageField(upload_to='plot_images'),
        ),
    ]
