# Generated by Django 2.2.6 on 2019-10-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectdetails', '0002_auto_20191028_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotdetails',
            name='plot_image',
            field=models.ImageField(upload_to='plot_images/'),
        ),
    ]
