# Generated by Django 2.2.6 on 2019-10-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectdetails', '0003_auto_20191028_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartmentdetails',
            name='cost_per_sqd',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=20),
        ),
        migrations.AddField(
            model_name='appartmentdetails',
            name='facing',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='appartmentdetails',
            name='other_exp',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='appartmentdetails',
            name='plot_image',
            field=models.ImageField(default=False, upload_to='plot_images/'),
        ),
        migrations.AddField(
            model_name='appartmentdetails',
            name='status',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='appartmentdetails',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=20),
        ),
    ]
