# Generated by Django 2.2.6 on 2019-10-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectdetails', '0004_auto_20191030_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appartmentdetails',
            name='plot_image',
        ),
        migrations.AddField(
            model_name='appartmentdetails',
            name='app_image',
            field=models.ImageField(default=False, upload_to='appartment_images/'),
        ),
    ]
