# Generated by Django 2.2.6 on 2019-10-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectdetails', '0005_auto_20191030_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appartmentdetails',
            old_name='cost_per_sqd',
            new_name='app_cost',
        ),
    ]
