# Generated by Django 2.2.6 on 2019-10-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectdetails', '0006_auto_20191030_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartmentdetails',
            name='app_area',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=20),
        ),
    ]
