# Generated by Django 2.2.6 on 2019-10-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectdetails', '0007_auto_20191030_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartmentdetails',
            name='app_area',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='appartmentdetails',
            name='app_cost',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='appartmentdetails',
            name='app_image',
            field=models.ImageField(upload_to='appartment_images/'),
        ),
        migrations.AlterField(
            model_name='appartmentdetails',
            name='facing',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='appartmentdetails',
            name='other_exp',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='appartmentdetails',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='appartmentdetails',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
