# Generated by Django 2.2.6 on 2019-10-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlotUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_cont_no', models.IntegerField()),
                ('user_mail', models.EmailField(max_length=254)),
                ('user_address', models.TextField()),
            ],
        ),
    ]
