# Generated by Django 2.2.6 on 2019-10-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotuser',
            name='user_address',
            field=models.CharField(max_length=200),
        ),
    ]
