# Generated by Django 2.2.6 on 2019-11-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191120_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
