# Generated by Django 2.2.6 on 2019-11-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_credentials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credentials',
            old_name='credential_namae',
            new_name='credential_name',
        ),
    ]
